CREATE TABLE `sap_sales_contract_header_data`
(
  `SalesContract`                   varchar(10) NOT NULL,
  `SalesContractType`               varchar(4) DEFAULT NULL,
  `SalesOrganization`               varchar(4) DEFAULT NULL,
  `DistributionChannel`             varchar(2) DEFAULT NULL,
  `OrganizationDivision`            varchar(2) DEFAULT NULL,
  `SalesGroup`                      varchar(3) DEFAULT NULL,
  `SalesOffice`                     varchar(4) DEFAULT NULL,
  `SalesDistrict`                   varchar(6) DEFAULT NULL,
  `SoldToParty`                     varchar(10) DEFAULT NULL,
  `CreationDate`                    varchar(80) DEFAULT NULL,
  `LastChangeDate`                  varchar(80) DEFAULT NULL,
  `PurchaseOrderByCustomer`         varchar(35) DEFAULT NULL,
  `CustomerPurchaseOrderDate`       varchar(80) DEFAULT NULL,
  `SalesContractDate`               varchar(80) DEFAULT NULL,
  `TotalNetAmount`                  varchar(13) DEFAULT NULL,
  `TransactionCurrency`             varchar(5) DEFAULT NULL,
  `SDDocumentReason`                varchar(3) DEFAULT NULL,
  `PricingDate`                     varchar(80) DEFAULT NULL,
  `IncotermsClassification`         varchar(3) DEFAULT NULL,
  `CustomerPaymentTerms`            varchar(4) DEFAULT NULL,
  `PaymentMethod`                   varchar(1) DEFAULT NULL,
  `SalesContractValidityStartDate`  varchar(80) DEFAULT NULL,
  `SalesContractValidityEndDate`    varchar(80) DEFAULT NULL,
  `SalesContractSignedDate`         varchar(80) DEFAULT NULL,
  `ReferenceSDDocument`             varchar(10) DEFAULT NULL,
  `ReferenceSDDocumentCategory`     varchar(4) DEFAULT NULL,
  `SalesDocApprovalStatus`          varchar(1) DEFAULT NULL,
  `SalesContractApprovalReason`     varchar(4) DEFAULT NULL,
  `OverallSDProcessStatus`          varchar(1) DEFAULT NULL,
  `TotalCreditCheckStatus`          varchar(1) DEFAULT NULL,
  `OverallSDDocumentRejectionSts`   varchar(1) DEFAULT NULL,
    PRIMARY KEY (`SalesContract`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
