CREATE TABLE `sap-sales-contract-header-data`
(
  `SalesContract`                   varchar(10) DEFAULT NULL,
  `SalesContractType`               varchar(4) DEFAULT NULL,
  `SalesOrganization`               varchar(4) DEFAULT NULL,
  `DistributionChannel`             varchar(2) DEFAULT NULL,
  `OrganizationDivision`            varchar(2) DEFAULT NULL,
  `SalesGroup`                      varchar(3) DEFAULT NULL,
  `SalesOffice`                     varchar(4) DEFAULT NULL,
  `SalesDistrict`                   varchar(6) DEFAULT NULL,
  `SoldToParty`                     varchar(10) DEFAULT NULL,
  `CreationDate`                    date DEFAULT NULL,
  `LastChangeDate`                  date DEFAULT NULL,
  `PurchaseOrderByCustomer`         varchar(35) DEFAULT NULL,
  `CustomerPurchaseOrderDate`       date DEFAULT NULL,
  `SalesContractDate`               date DEFAULT NULL,
  `TotalNetAmount`                  varchar(13) DEFAULT NULL,
  `TransactionCurrency`             varchar(5) DEFAULT NULL,
  `SDDocumentReason`                varchar(3) DEFAULT NULL,
  `PricingDate`                     date DEFAULT NULL,
  `IncotermsClassification`         varchar(3) DEFAULT NULL,
  `CustomerPaymentTerms`            varchar(4) DEFAULT NULL,
  `PaymentMethod`                   varchar(1) DEFAULT NULL,
  `SalesContractValidityStartDate`  date DEFAULT NULL,
  `SalesContractValidityEndDate`    date DEFAULT NULL,
  `SalesContractSignedDate`         date DEFAULT NULL,
  `ReferenceSDDocument`             varchar(10) DEFAULT NULL,
  `ReferenceSDDocumentCategory`     varchar(4) DEFAULT NULL,
  `SalesDocApprovalStatus`          varchar(1) DEFAULT NULL,
  `SalesContractApprovalReason`     varchar(4) DEFAULT NULL,
  `OverallSDProcessStatus`          varchar(1) DEFAULT NULL,
  `TotalCreditCheckStatus`          varchar(1) DEFAULT NULL,
  `OverallSDDocumentRejectionSts`   varchar(1) DEFAULT NULL,
    PRIMARY KEY (`SalesContract`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
